version: "3.8"

services:
  db:
    build:
      context: ./mongo/
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    healthcheck:
      test: |
        test $$(mongosh --quiet -u root -p root --eval "try { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'db' }] }).ok } catch (_) { rs.status().ok }") -eq 1
      interval: 10s
      start_period: 30s
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./nginx-localhost.conf:/etc/nginx/nginx.conf:ro

volumes:
  mongodb_data:
