version: "3"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command: npm run start:ci
    container_name: app
    depends_on:
      - db
    env_file: .env
    environment:
      NEXTAUTH_URL: https://localhost
      MONGO_URI: mongodb://root:root@db/jp-test?authSource=admin&tls=false
    restart: always
  db:
    image: mongo:7
    container_name: db
    command: --replSet rs0 --bind_ip_all --keyFile /keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo/keyfile:/keyfile
    healthcheck:
      test: |
        test $$(mongosh --quiet -u root -p root --eval "try { rs.initiate().ok } catch (_) { rs.status().ok }") -eq 1
      start_period: 30s
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    restart: unless-stopped
    env_file: .env
    environment:
      - SERVER_NAME=localhost
      - CERTBOT_EMAIL=test@journaling.place
      - USE_LOCAL_CA=1
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx:/etc/nginx/templates

volumes:
  nginx_secrets:
  mongodb_data:
