version: "3"

services:
  app:
    build: .
    command: npm run start
    env_file: .env
    restart: always
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/templates
