version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    command: npm run dev
    env_file: .env
    environment:
      - NEXT_PUBLIC_NEXTAUTH_URL=https://localhost
      - NEXTAUTH_URL=https://localhost
    restart: always
    volumes:
      - /app/node_modules
      - ./:/app
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - SERVER_NAME=localhost
      - CERTBOT_EMAIL=test@journaling.place
      - USE_LOCAL_CA=1
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx:/etc/nginx/templates

volumes:
  nginx_secrets:
