services:
  app:
    image: tmshkr/journaling.place:${DOCKER_TAG}
    command: npm run start
    container_name: app
    environment:
      EMAIL_FROM:
      EMAIL_SECRET:
      EMAIL_SERVER:
      MONGO_URI:
      NEXTAUTH_SECRET:
      NEXTAUTH_URL: https://${TARGET_DOMAIN}
      PRISMA_QUERY_ENGINE_LIBRARY: /app/node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-3.0.x.so.node
      TEST_USER_EMAIL:
      VERSION_LABEL:
    restart: always
    healthcheck:
      test: "curl -f http://app:3000 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /app/node_modules
  caddy:
    image: caddy
    container_name: caddy
    environment:
      TLS_AUTO_EMAIL: "${TLS_AUTO_EMAIL:-internal}"
      SERVER_NAME: "${TARGET_DOMAIN} ${CNAME}"
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - "${MOUNT_DIRECTORY}/${STAGE}/caddy/data:/data"
      - "${MOUNT_DIRECTORY}/${STAGE}/caddy/config:/config"
