services:
  app:
    image: tmshkr/journaling.place:${GITHUB_SHA}
    command: npm run start
    container_name: app
    env_file: .env
    restart: always
    healthcheck:
      test: "curl -f http://app:3000 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /app/node_modules
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "443:443"
    volumes:
      - ./cf-cert.pem:/etc/nginx/certs/cf-cert.pem
      - ./cf-key.pem:/etc/nginx/certs/cf-key.pem
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template
