version: "3"

services:
  app:
    image: 983436253905.dkr.ecr.us-west-2.amazonaws.com/journaling.place:${SHA}
    command: npm run start
    env_file: .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 600m
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /efs/${ENVIRONMENT}/letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/templates
    deploy:
      resources:
        limits:
          memory: 100m
