services:
  app:
    image: tmshkr/journaling.place:${DOCKER_TAG}
    command: npm run start
    container_name: app
    environment:
      EMAIL_FROM:
      EMAIL_SECRET:
      EMAIL_SERVER:
      MONGO_URI:
      NEXTAUTH_SECRET:
      NEXTAUTH_URL: https://${TARGET_DOMAIN}
      PRISMA_QUERY_ENGINE_LIBRARY: /app/node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-3.0.x.so.node
      VERSION_LABEL:
    restart: always
    healthcheck:
      test: "curl -f http://app:3000 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /app/node_modules
  nginx:
    image: nginx:alpine
    container_name: nginx
    environment:
      TARGET_DOMAIN:
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "443:443"
    volumes:
      - ./cf-cert.pem:/etc/nginx/certs/cf-cert.pem
      - ./cf-key.pem:/etc/nginx/certs/cf-key.pem
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template
