version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    command: npm run dev
    env_file: .env
    restart: always
    volumes:
      - /app/node_modules
      - ./:/app
    depends_on:
      - nginx
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
      - "5555:5555"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx:/etc/nginx/user_conf.d

volumes:
  nginx_secrets:
