version: "3.8"

services:
  app:
    image: app:test
    build:
      dockerfile: Dockerfile
    pull_policy: never
    command: npm run start
    container_name: app
    depends_on:
      - db
    env_file: .env
    environment:
      MONGO_URI: mongodb://$MONGO_USER:$MONGO_PASSWORD@db/jp-test?authSource=admin&tls=false
    restart: always
    volumes:
      - /app/node_modules
  db:
    build:
      context: ./mongo/
    container_name: db
    attach: false
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    healthcheck:
      test: |
        test $$(mongosh --quiet -u $MONGO_USER -p $MONGO_PASSWORD --eval "try { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'db' }] }).ok } catch (_) { rs.status().ok }") -eq 1
      interval: 10s
      start_period: 30s
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mongodb_data:
