version: "3"

services:
  app:
    image: ${DOCKER_REGISTRY}/journaling.place:${TAG}
    command: npm run start
    container_name: app
    env_file: .env
    restart: always
    volumes:
      - /app/node_modules
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL:
      SERVER_NAME:
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /efs/${ENVIRONMENT}/letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/templates
  mongo-backup:
    image: "tmshkr/mongodump"
    environment:
      CRON_SCHEDULE: "0 10 * * *"
      MONGO_URI:
      TARGET_FOLDER: "/backup"
      TARGET_S3_FOLDER: "${MONGO_BACKUP_S3_FOLDER}"
