version: "3.8"

services:
  app:
    image: ${DOCKER_REGISTRY}/journaling.place:${TAG}
    command: npm run start
    container_name: app
    env_file: .env
    restart: always
    volumes:
      - /app/node_modules
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  mongo-backup:
    image: "tmshkr/mongodump"
    environment:
      CRON_SCHEDULE: "0 10 * * *"
      MONGO_URI:
      TARGET_FOLDER: "/backup"
      TARGET_S3_FOLDER: "s3://${BACKUP_BUCKET_NAME}/${ENVIRONMENT}"
