version: "3.8"

services:
  app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/journaling.place:${TAG}
    command: npm run start
    container_name: app
    env_file: .env
    restart: always
    volumes:
      - /app/node_modules
  nginx:
    image: jonasal/nginx-certbot:5-alpine
    container_name: nginx
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL:
      DOMAIN_NAME:
      SERVER_NAME:
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /efs/letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/templates
  mongo-backup:
    image: "tmshkr/mongodump"
    environment:
      CRON_SCHEDULE: "0 10 * * *"
      MONGO_URI:
      TARGET_FOLDER: "/backup"
      TARGET_S3_FOLDER: "s3://${BACKUP_BUCKET_NAME}/${ENVIRONMENT}"
