AWSTemplateFormatVersion: 2010-09-09

Description: Creates the necessary roles to deploy an EC2 instance via Elastic Beanstalk, along with an OIDC provider and role for use with GitHub Actions.

Parameters:
  AudienceList:
    Type: CommaDelimitedList
    Default: sts.amazonaws.com
    Description: >
      Comma-separated list of allowed audiences for the tokens.
      Default is audience for the official AWS configure action from https://github.com/aws-actions/configure-aws-credentials
  SubjectClaimFilters:
    Type: CommaDelimitedList
    Description: >
      Subject claim filter for valid tokens.
      See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#example-subject-claims
      for examples of fitlering by branch or deployment environment.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "GitHub Actions Configuration"
        Parameters:
          - SubjectClaimFilters
          - AudienceList

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier"
        - "arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker"
        - "arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier"
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
      RoleName: "aws-elasticbeanstalk-ec2-role"
  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref "InstanceRole"
      InstanceProfileName: "aws-elasticbeanstalk-ec2-role"
  GitHubIdentityProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList: !Ref AudienceList
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
        - 1b511abead59c6ce207077c0bf0e0043b1382612
      Url: https://token.actions.githubusercontent.com
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHubIdentityProvider.Arn
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": !Ref AudienceList
              StringLike:
                "token.actions.githubusercontent.com:sub": !Ref SubjectClaimFilters
      Description: IAM Role for use with GitHub Actions
      RoleName: GitHubActions
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess-AWSElasticBeanstalk"
        - "arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess"
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "elasticbeanstalk.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth"
        - "arn:aws:iam::aws:policy/AWSElasticBeanstalkManagedUpdatesCustomerRolePolicy"
      Path: "/service-role/"
      RoleName: "aws-elasticbeanstalk-service-role"

Outputs:
  RoleARN:
    Description: ARN of IAM role for use with GitHub Actions
    Value: !GetAtt GitHubActionsRole.Arn
