name: Blue/Green Deployment
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - staging
  push:
    branches:
      - main
      - staging
env:
  DOCKER_IMAGE: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/journaling.place
  GH_ACTIONS_ROLE: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GitHubActions
  STAGE: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      skip_build: ${{ steps.prep.outputs.SKIP_BUILD }}
      turbo_tag: ${{ steps.prep.outputs.TURBO_TAG }}
      version_label: ${{ steps.prep.outputs.VERSION_LABEL }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.GH_ACTIONS_ROLE }}
      - id: prep
        name: Deployment prep
        run: ./scripts/deployment-prep.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_EVENT: ${{ toJson(github.event) }}
      - id: deploy
        name: Deploy
        uses: tmshkr/blue-green-beanstalk@v5
        with:
          app_name: "journaling.place"
          blue_env: ${{ vars.BLUE_ENV }}
          deploy: true
          disable_termination_protection: true
          green_env: ${{ vars.GREEN_ENV }}
          option_settings: option-settings.json
          platform_branch_name: "Docker running on 64bit Amazon Linux 2023"
          production_cname: ${{ vars.PRODUCTION_CNAME }}
          source_bundle: bundle.zip
          staging_cname: ${{ vars.STAGING_CNAME }}
          update_listener_rules: true
          version_description: ${{ github.event.head_commit.message }}
          version_label: ${{ steps.prep.outputs.VERSION_LABEL }}
          wait_for_deployment: false

  build:
    needs: deploy
    if: needs.deploy.outputs.skip_build != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.GH_ACTIONS_ROLE }}
      - name: Setup turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          platforms: linux/amd64
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build
        uses: docker/build-push-action@v6
        with:
          build-args: CDN_PREFIX=https://cdn.journaling.place
          cache-from: type=gha
          context: .
          load: true
          provenance: false
          tags: ${{ env.DOCKER_IMAGE }}:builder
          target: builder
      - name: Export turbo cache and static assets
        run: ./scripts/docker-export.sh
        env:
          CDN_BUCKET: ${{ vars.CDN_BUCKET }}
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
      - name: Push runner image
        uses: docker/build-push-action@v6
        with:
          build-args: CDN_PREFIX=https://cdn.journaling.place
          cache-to: type=gha,mode=max
          context: .
          provenance: false
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ needs.deploy.outputs.turbo_tag }}
            ${{ env.DOCKER_IMAGE }}:${{ needs.deploy.outputs.version_label }}
            ${{ env.DOCKER_IMAGE }}:build.${{ needs.deploy.outputs.version_label }}
            ${{ env.DOCKER_IMAGE }}:expire.${{ needs.deploy.outputs.version_label }}
            ${{ env.DOCKER_IMAGE }}:latest

  test:
    if: always() && needs.deploy.result == 'success' && (needs.build.result == 'success' || needs.build.result == 'skipped')
    needs: [deploy, build]
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.GH_ACTIONS_ROLE }}
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 22
      - name: Install e2e deps
        run: npm run install:ci --workspace=e2e
      - name: Wait for environment
        uses: tmshkr/blue-green-beanstalk@v5
        with:
          app_name: "journaling.place"
          blue_env: ${{ vars.BLUE_ENV }}
          green_env: ${{ vars.GREEN_ENV }}
          minimum_health_color: Yellow
          production_cname: ${{ vars.PRODUCTION_CNAME }}
          staging_cname: ${{ vars.STAGING_CNAME }}
          terminate_unhealthy_environment: false
      - name: Run e2e tests
        run: npm run test --workspace=e2e
        env:
          BASE_URL: https://staging.journaling.place
          CF_SKIP_TOKEN: ${{ secrets.CF_SKIP_TOKEN }}
          TEST_USER_EMAIL: ${{ vars.TEST_USER_EMAIL }}
          VERSION_LABEL: ${{ needs.deploy.outputs.version_label }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/e2e/playwright-report/
          retention-days: 30

  promote:
    if: always() && needs.test.result == 'success' && github.ref_name == 'main'
    needs: [deploy, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.GH_ACTIONS_ROLE }}
      - name: Promote
        uses: tmshkr/blue-green-beanstalk@v5
        with:
          app_name: "journaling.place"
          blue_env: ${{ vars.BLUE_ENV }}
          enable_termination_protection: true
          green_env: ${{ vars.GREEN_ENV }}
          production_cname: ${{ vars.PRODUCTION_CNAME }}
          send_command: ./scripts/promote.sh
          staging_cname: ${{ vars.STAGING_CNAME }}
          swap_cnames: true
          update_listener_rules: true
      - run: ./scripts/tag-image.mjs
        env:
          CURRENT_TAG: ${{ needs.deploy.outputs.version_label }}
          NEW_TAGS: production
          TAGS_TO_REMOVE: expire.${{ needs.deploy.outputs.version_label }}

  verify:
    if: always() && needs.promote.result == 'success'
    needs: [deploy, promote]
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.GH_ACTIONS_ROLE }}
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 22
      - name: Install e2e deps
        run: npm run install:ci --workspace=e2e
      - id: test
        name: Run e2e tests
        run: npm run test --workspace=e2e
        env:
          BASE_URL: https://journaling.place
          CF_SKIP_TOKEN: ${{ secrets.CF_SKIP_TOKEN }}
          TEST_USER_EMAIL: ${{ vars.TEST_USER_EMAIL }}
          VERSION_LABEL: ${{ needs.deploy.outputs.version_label }}
      - name: Rollback
        if: ${{ failure() && steps.test.conclusion == 'failure' }}
        uses: tmshkr/blue-green-beanstalk@v5
        with:
          app_name: "journaling.place"
          blue_env: ${{ vars.BLUE_ENV }}
          green_env: ${{ vars.GREEN_ENV }}
          minimum_health_color: Yellow
          production_cname: ${{ vars.PRODUCTION_CNAME }}
          staging_cname: ${{ vars.STAGING_CNAME }}
          swap_cnames: true
          update_listener_rules: true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/e2e/playwright-report/
          retention-days: 30
