name: GCP Blue/Green Deployment
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION_LABEL: ${{ github.ref_name }}.${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          platforms: linux/amd64
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          context: .
          load: true
          tags: tmshkr/journaling.place:builder
          target: builder
      - name: Export turbo cache and static assets
        run: ./scripts/docker-export.sh
        env:
          CDN_BUCKET: ${{ vars.CDN_BUCKET }}
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
      - name: Push runner image
        uses: docker/build-push-action@v6
        with:
          cache-to: type=gha,mode=max
          context: .
          push: true
          tags: |
            tmshkr/journaling.place:${{ env.VERSION_LABEL }}
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: "actions/checkout@v4"
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - run: terraform -chdir=terraform/compute init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"
      - run: ./scripts/terraform/deploy.sh
        env:
          BLUE_ENV: ${{ vars.BLUE_ENV }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DOCKER_TAG: ${{ vars.DOCKER_TAG }}
          EMAIL_FROM: ${{ vars.EMAIL_FROM }}
          EMAIL_SECRET: ${{ secrets.EMAIL_SECRET }}
          EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          GCP_ZONE: ${{ vars.GCP_ZONE }}
          GREEN_ENV: ${{ vars.GREEN_ENV }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          ORIGIN_CERT: ${{ secrets.ORIGIN_CERT }}
          ORIGIN_KEY: ${{ secrets.ORIGIN_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          PRODUCTION_DOMAIN: ${{ vars.PRODUCTION_DOMAIN }}
          STAGING_DOMAIN: ${{ vars.STAGING_DOMAIN }}
          TEST_USER_EMAIL: ${{ vars.TEST_USER_EMAIL }}
          TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}
          VERSION_LABEL: ${{ github.ref_name}}.${{ github.sha }}
