name: GCP Blue/Green Deployment
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: "staging"
        options:
          - "staging"
          - "production"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      skip_build: ${{ steps.turbo_tag.outputs.SKIP_BUILD }}
      turbo_tag: ${{ steps.turbo_tag.outputs.TURBO_TAG }}
      version_label: ${{ steps.turbo_tag.outputs.VERSION_LABEL }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          platforms: linux/amd64
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: turbo_tag
        run: ./scripts/turbo-sha.mjs
      - if: steps.turbo_tag.outputs.SKIP_BUILD != 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run build.yml --ref ${{ github.ref_name }} \
          -f turbo_tag=${{ steps.turbo_tag.outputs.TURBO_TAG }} \
          -f version_label=${{ steps.turbo_tag.outputs.VERSION_LABEL }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - run: terraform -chdir=terraform/compute init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"
      - run: ./scripts/terraform/deploy.sh
        env:
          BLUE_ENV: ${{ vars.BLUE_ENV }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DOCKER_TAG: ${{ steps.turbo_tag.outputs.version_label }}
          EMAIL_FROM: ${{ vars.EMAIL_FROM }}
          EMAIL_SECRET: ${{ secrets.EMAIL_SECRET }}
          EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          GCP_ZONE: ${{ vars.GCP_ZONE }}
          GREEN_ENV: ${{ vars.GREEN_ENV }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          ORIGIN_CERT: ${{ secrets.ORIGIN_CERT }}
          ORIGIN_KEY: ${{ secrets.ORIGIN_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          PRODUCTION_DOMAIN: ${{ vars.PRODUCTION_DOMAIN }}
          STAGING_DOMAIN: ${{ vars.STAGING_DOMAIN }}
          TEST_USER_EMAIL: ${{ vars.TEST_USER_EMAIL }}
          TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}
          VERSION_LABEL: ${{ steps.turbo_tag.outputs.version_label }}

  test:
    needs: [deploy]
    environment: staging
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 22
      - name: Install e2e deps
        run: npm run install:ci --workspace=e2e
      - name: Run e2e tests
        run: npm run test --workspace=e2e
        env:
          BASE_URL: ${{ vars.NEXTAUTH_URL }}
          CF_SKIP_TOKEN: ${{ secrets.CF_SKIP_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          TEST_USER_EMAIL: ${{ vars.TEST_USER_EMAIL }}
          VERSION_LABEL: ${{ needs.deploy.outputs.version_label }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-test
          path: packages/e2e/playwright-report/
          retention-days: 30

  promote:
    if: inputs.environment == 'production'
    environment: production
    needs: [deploy, test]
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - uses: "actions/checkout@v4"
      - run: su -c "apt-get update && apt-get install unzip -y"
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - run: terraform -chdir=terraform/compute init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 22
      - name: Install e2e deps
        run: npm run install:ci --workspace=e2e
      - name: Promote
        run: ./scripts/terraform/promote.sh
        env:
          BLUE_ENV: ${{ vars.BLUE_ENV }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DOCKER_TAG: ${{ needs.deploy.outputs.version_label }}
          EMAIL_FROM: ${{ vars.EMAIL_FROM }}
          EMAIL_SECRET: ${{ secrets.EMAIL_SECRET }}
          EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          GCP_ZONE: ${{ vars.GCP_ZONE }}
          GREEN_ENV: ${{ vars.GREEN_ENV }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          ORIGIN_CERT: ${{ secrets.ORIGIN_CERT }}
          ORIGIN_KEY: ${{ secrets.ORIGIN_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          PRODUCTION_DOMAIN: ${{ vars.PRODUCTION_DOMAIN }}
          STAGING_DOMAIN: ${{ vars.STAGING_DOMAIN }}
          TEST_USER_EMAIL: ${{ vars.TEST_USER_EMAIL }}
          TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}
          VERSION_LABEL: ${{ needs.deploy.outputs.version_label }}
      - name: Run e2e tests
        run: npm run test --workspace=e2e
        env:
          BASE_URL: ${{ vars.NEXTAUTH_URL }}
          CF_SKIP_TOKEN: ${{ secrets.CF_SKIP_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          TEST_USER_EMAIL: ${{ vars.TEST_USER_EMAIL }}
          VERSION_LABEL: ${{ needs.deploy.outputs.version_label }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-promote
          path: packages/e2e/playwright-report/
          retention-days: 30
