name: GCP Blue/Green Deployment
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: "actions/checkout@v4"
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - run: terraform -chdir=terraform/compute init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"
      - run: ./scripts/terraform/deploy.sh
        env:
          BLUE_ENV: ${{ vars.BLUE_ENV }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          EMAIL_FROM: ${{ vars.EMAIL_FROM }}
          EMAIL_SECRET: ${{ secrets.EMAIL_SECRET }}
          EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          GCP_ZONE: ${{ vars.GCP_ZONE }}
          GREEN_ENV: ${{ vars.GREEN_ENV }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          ORIGIN_CERT: ${{ secrets.ORIGIN_CERT }}
          ORIGIN_KEY: ${{ secrets.ORIGIN_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: https://${{ vars.STAGING_DOMAIN }}
          PRODUCTION_DOMAIN: ${{ vars.PRODUCTION_DOMAIN }}
          STAGING_DOMAIN: ${{ vars.STAGING_DOMAIN }}
          TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}
