name: Playwright Test
on:
  workflow_dispatch:
    inputs:
      NGROK_TUNNELS:
        type: string
        required: true
      SSH_COMMAND:
        type: string
        required: true
      SSH_HOST_PUBLIC_KEY:
        type: string
        required: true

jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 21
      - name: Install e2e deps
        run: npm run install:ci --workspace=e2e
      - name: Run e2e tests
        run: |
          export BASE_URL=$(echo ${{ inputs.NGROK_TUNNELS }} | jq -r '.[] | select(.name == "web") | .public_url')
          npm run test --workspace=e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/e2e/playwright-report/
          retention-days: 30
