name: Test
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - "staging"
          - "production"
          - "test"
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 22
      - name: Install e2e deps
        run: npm run install:ci --workspace=e2e
      - name: Run e2e tests
        run: npm run test --workspace=e2e
        env:
          BASE_URL: ${{ vars.NEXTAUTH_URL }}
          CF_SKIP_TOKEN: ${{ secrets.CF_SKIP_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          TEST_USER_EMAIL: ${{ vars.TEST_USER_EMAIL }}
          VERSION_LABEL: ${{ github.ref_name }}.${{ github.sha }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-test
          path: packages/e2e/playwright-report/
          retention-days: 30
