name: Run Tests
on:
  workflow_dispatch:

jobs:
  test:
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get env file
        run: aws s3 cp s3://${{ vars.CONFIG_S3_BUCKET }}/test.env .env
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      - name: Start docker compose
        run: docker compose -f docker-compose.test.yml up -d
      - name: Install Dependencies
        run: npm install && npx playwright install --with-deps chromium
      - name: Run unit tests
        run: npm run jest
      - name: Wait for server
        run: ./scripts/wait-for-server.sh https://localhost
      - name: Run e2e tests
        run: npm run e2e:test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/e2e/playwright-report/
          retention-days: 30
      - name: Stop docker compose
        if: always()
        run: docker compose -f docker-compose.test.yml down
