name: Run Tests on localhost
on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      db:
        image: mongo:7
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
          - mongodb_data:/data/db
      nginx:
        image: nginx:alpine
        ports:
          - 80:80
        options: "host"
        volumes:
          - nginx:/etc/nginx/
    container:
      image: node:21-alpine
      volumes:
        - nginx:/nginx/test/
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 21
      - name: Setup ngrok-ssh
        uses: tmshkr/ngrok-ssh@v1
        with:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
          NGROK_CONFIG_FILE: "ngrok.yml"
      # - name: build
      #   run: npm ci && npm run build
      - name: Start app
        run: npx -y serve
        # env:
        #   EMAIL_FROM: ${{ vars.EMAIL_FROM }}
        #   EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
        #   NEXT_PUBLIC_VERSION: "test-${{ github.sha }}"
        #   NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
