name: Run Tests
on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Get env vars
        run: |
          echo "test" > ENVIRONMENT
          echo ${{ github.sha }} > SHA
          ./.platform/hooks/prebuild/get-env-vars.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
      - name: Start docker compose
        run: docker compose -f docker-compose.test.yml up -d
      - name: Install e2e deps
        run: npm run install:ci --workspace=e2e
      - name: Wait for server
        run: ./scripts/wait-for-server.sh https://localhost test-${{ github.sha }}
      - name: Run e2e tests
        run: npm run test --workspace=e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/e2e/playwright-report/
          retention-days: 30
      - name: Stop docker compose
        if: always()
        run: docker compose -f docker-compose.test.yml down
