name: Run Tests
on:
  workflow_dispatch:

jobs:
  build_and_serve:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup ngrok-ssh
        id: ngrok-ssh
        uses: tmshkr/ngrok-ssh@dev
        with:
          BASH_PROFILE: ".bash_profile"
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
          NGROK_CONFIG_FILE: "ngrok.yml"
          SSH_CLIENT_PUBLIC_KEY: ${{ vars.SSH_PUBLIC_KEY }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Build
        uses: docker/build-push-action@v5
        env:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        with:
          load: true
          push: false
          tags: app:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run Playwright workflow
        id: run-playwright
        run: ./scripts/run-playwright-workflow.sh
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          MONGO_USER: ${{ vars.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          NGROK_TUNNELS: ${{ steps.ngrok-ssh.outputs.NGROK_TUNNELS }}
          SSH_HOSTNAME: ${{ steps.ngrok-ssh.outputs.SSH_HOSTNAME }}
          SSH_PORT: ${{ steps.ngrok-ssh.outputs.SSH_PORT }}
          SSH_HOST_PUBLIC_KEY: ${{ steps.ngrok-ssh.outputs.SSH_HOST_PUBLIC_KEY }}
          SSH_USER: ${{ steps.ngrok-ssh.outputs.SSH_USER }}
      - uses: tmshkr/handle-env@dev
        with:
          env: |
            APP_VERSION=test-${{ github.sha }}
            EMAIL_FROM=${{ vars.EMAIL_FROM }}
            EMAIL_SERVER=${{ secrets.EMAIL_SERVER }}
            MONGO_USER=${{ vars.MONGO_USER }}
            MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL=${{ steps.run-playwright.outputs.BASE_URL }}
      - name: Start docker compose
        run: docker compose -f docker-compose.test.yml up
